openapi: 3.0.1
info:
  title: IBS Wizz card API
  description: IBS Wizz card API
  termsOfService: http://finik.pro/terms/
  contact:
    name: API Support
    url: http://finik.pro/support
    email: support@finik.pro
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.1.0
servers:
  - url: '@@SERVER_URL@@'